// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netmsg.proto

#ifndef PROTOBUF_netmsg_2eproto__INCLUDED
#define PROTOBUF_netmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace MessageCode {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_netmsg_2eproto();
void protobuf_AssignDesc_netmsg_2eproto();
void protobuf_ShutdownFile_netmsg_2eproto();

class ProtoLoginReq;
class ProtoLoginRes;

// ===================================================================

class ProtoLoginReq : public ::google::protobuf::Message {
 public:
  ProtoLoginReq();
  virtual ~ProtoLoginReq();

  ProtoLoginReq(const ProtoLoginReq& from);

  inline ProtoLoginReq& operator=(const ProtoLoginReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoLoginReq& default_instance();

  void Swap(ProtoLoginReq* other);

  // implements Message ----------------------------------------------

  ProtoLoginReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoLoginReq& from);
  void MergeFrom(const ProtoLoginReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 authID = 1;
  inline bool has_authid() const;
  inline void clear_authid();
  static const int kAuthIDFieldNumber = 1;
  inline ::google::protobuf::int32 authid() const;
  inline void set_authid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MessageCode.ProtoLoginReq)
 private:
  inline void set_has_authid();
  inline void clear_has_authid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 authid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_netmsg_2eproto();
  friend void protobuf_AssignDesc_netmsg_2eproto();
  friend void protobuf_ShutdownFile_netmsg_2eproto();

  void InitAsDefaultInstance();
  static ProtoLoginReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoLoginRes : public ::google::protobuf::Message {
 public:
  ProtoLoginRes();
  virtual ~ProtoLoginRes();

  ProtoLoginRes(const ProtoLoginRes& from);

  inline ProtoLoginRes& operator=(const ProtoLoginRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoLoginRes& default_instance();

  void Swap(ProtoLoginRes* other);

  // implements Message ----------------------------------------------

  ProtoLoginRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoLoginRes& from);
  void MergeFrom(const ProtoLoginRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 mapID = 1;
  inline bool has_mapid() const;
  inline void clear_mapid();
  static const int kMapIDFieldNumber = 1;
  inline ::google::protobuf::int32 mapid() const;
  inline void set_mapid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MessageCode.ProtoLoginRes)
 private:
  inline void set_has_mapid();
  inline void clear_has_mapid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 mapid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_netmsg_2eproto();
  friend void protobuf_AssignDesc_netmsg_2eproto();
  friend void protobuf_ShutdownFile_netmsg_2eproto();

  void InitAsDefaultInstance();
  static ProtoLoginRes* default_instance_;
};
// ===================================================================


// ===================================================================

// ProtoLoginReq

// required int32 authID = 1;
inline bool ProtoLoginReq::has_authid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoLoginReq::set_has_authid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoLoginReq::clear_has_authid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoLoginReq::clear_authid() {
  authid_ = 0;
  clear_has_authid();
}
inline ::google::protobuf::int32 ProtoLoginReq::authid() const {
  return authid_;
}
inline void ProtoLoginReq::set_authid(::google::protobuf::int32 value) {
  set_has_authid();
  authid_ = value;
}

// -------------------------------------------------------------------

// ProtoLoginRes

// required int32 mapID = 1;
inline bool ProtoLoginRes::has_mapid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoLoginRes::set_has_mapid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoLoginRes::clear_has_mapid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoLoginRes::clear_mapid() {
  mapid_ = 0;
  clear_has_mapid();
}
inline ::google::protobuf::int32 ProtoLoginRes::mapid() const {
  return mapid_;
}
inline void ProtoLoginRes::set_mapid(::google::protobuf::int32 value) {
  set_has_mapid();
  mapid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MessageCode

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_netmsg_2eproto__INCLUDED
